# PacketRaft WireGuard Configuration
# Generated: 2026-08-30T13:37:07.579997

[Interface]
PrivateKey = RyqoJLItAQVXW7QRq+HTrL3cK4bcI+jEDDg+ioZfVhQ=
Address = 10.88.140.101/24
DNS = 8.8.8.8, 8.8.4.4
MTU = 1420
PersistentKeepalive = 25

[Peer]
PublicKey = ui9o3e1D7x1QnFJUX7PzROMOXnhXXelfF+5HgnhD2TA=
Endpoint = ir1.packetraft.ir:51820
AllowedIPs = 0.0.0.0/0, ::/0